# Generated by Django 4.0.4 on 2022-05-01 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=100, verbose_name='Английское слово')),
                ('transcription', models.CharField(max_length=100, verbose_name='Транскрипция')),
                ('translation', models.CharField(max_length=100, verbose_name='Перевод')),
                ('note', models.CharField(max_length=100, verbose_name='Заметка')),
                ('favourite', models.BooleanField(default=False, verbose_name='Избранное ли слово')),
                ('category', models.CharField(choices=[('ZERO', 'Zero'), ('ONE', 'One'), ('TWO', 'Two'), ('THREE', 'Three')], default='Zero', max_length=5, verbose_name='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dictionary', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Word',
                'verbose_name_plural': 'Words',
                'db_table': 'word_table',
                'managed': True,
            },
        ),
    ]
