# Generated by Django 4.0.4 on 2022-05-01 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='english',
            field=models.CharField(max_length=100, unique=True, verbose_name='Английское слово'),
        ),
        migrations.AlterField(
            model_name='word',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Заметка'),
        ),
    ]
