# Generated by Django 4.0.4 on 2022-05-15 23:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dictionary', '0005_alter_dictionarysetting_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='english',
            field=models.CharField(max_length=100, verbose_name='Английское слово'),
        ),
        migrations.AlterUniqueTogether(
            name='word',
            unique_together={('user', 'english')},
        ),
    ]
