# Generated by Django 4.0.4 on 2022-06-11 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0006_alter_word_english_alter_word_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'managed': True, 'ordering': ('english',), 'verbose_name': 'Word', 'verbose_name_plural': 'Words'},
        ),
        migrations.AddField(
            model_name='word',
            name='pure_translation',
            field=models.CharField(default='', max_length=200, verbose_name='Чистый перевод'),
        ),
        migrations.AlterField(
            model_name='word',
            name='category',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], default='0', max_length=5, verbose_name='Категория'),
        ),
    ]
