# Generated by Django 4.0.4 on 2022-06-14 00:46

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0008_runword'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='runword',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='runword',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Статус активности'),
        ),
    ]
