# Generated by Django 4.0.4 on 2022-06-14 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0009_alter_runword_managers_runword_status'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='runword',
            managers=[
            ],
        ),
    ]
