# Generated by Django 4.0.4 on 2022-06-22 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dictionary', '0011_runword_user_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='runword',
            old_name='status',
            new_name='active_status',
        ),
        migrations.AddField(
            model_name='runword',
            name='answer_status',
            field=models.BooleanField(default=False, verbose_name='Статус правильности ответа'),
        ),
        migrations.CreateModel(
            name='RunSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_type', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('is_use_favourite', models.BooleanField(default=False)),
                ('is_endless', models.BooleanField(default=False)),
                ('is_answer_menu', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
