# Generated by Django 4.0.4 on 2022-07-01 16:14

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0012_rename_status_runword_active_status_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='runword',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='runsettings',
            name='category',
        ),
        migrations.RemoveField(
            model_name='runsettings',
            name='is_use_favourite',
        ),
        migrations.AlterField(
            model_name='runword',
            name='active_status',
            field=models.BooleanField(default=True, verbose_name='Появилось ли слово'),
        ),
    ]
